// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShadowGaze.Data.Services.Database;

#nullable disable

namespace ShadowGaze.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250904105121_AddPayments")]
    partial class AddPayments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ShadowGaze.Data.Models.Database.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Balance")
                        .HasColumnType("double precision")
                        .HasColumnName("balance");

                    b.Property<int?>("EndpointId")
                        .HasColumnType("integer")
                        .HasColumnName("endpoint_id");

                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_id");

                    b.Property<string>("TelegramName")
                        .HasColumnType("text")
                        .HasColumnName("telegram_name");

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.HasIndex("EndpointId")
                        .IsUnique()
                        .HasDatabaseName("ix_customers_endpoint_id");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("ShadowGaze.Data.Models.Database.Endpoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<string>("ConnectionString")
                        .HasColumnType("text")
                        .HasColumnName("connection_string");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("expiry_date");

                    b.Property<int>("InboundId")
                        .HasColumnType("integer")
                        .HasColumnName("inbound_id");

                    b.Property<int>("XrayId")
                        .HasColumnType("integer")
                        .HasColumnName("xray_id");

                    b.HasKey("Id")
                        .HasName("pk_endpoints");

                    b.HasIndex("XrayId")
                        .HasDatabaseName("ix_endpoints_xray_id");

                    b.ToTable("endpoints", (string)null);
                });

            modelBuilder.Entity("ShadowGaze.Data.Models.Database.Instructions.PlatformInstruction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationName")
                        .HasColumnType("text")
                        .HasColumnName("application_name");

                    b.Property<string>("ApplicationUrl")
                        .HasColumnType("text")
                        .HasColumnName("application_url");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("Platform")
                        .HasColumnType("integer")
                        .HasColumnName("platform");

                    b.Property<int?>("TelegramFileId")
                        .HasColumnType("integer")
                        .HasColumnName("telegram_file_id");

                    b.HasKey("Id")
                        .HasName("pk_platform_instructions");

                    b.HasIndex("TelegramFileId")
                        .HasDatabaseName("ix_platform_instructions_telegram_file_id");

                    b.ToTable("platform_instructions", (string)null);
                });

            modelBuilder.Entity("ShadowGaze.Data.Models.Database.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Currency")
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<string>("InvoicePayload")
                        .HasColumnType("text")
                        .HasColumnName("invoice_payload");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("payment_date");

                    b.Property<string>("ProviderPaymentChargeId")
                        .HasColumnType("text")
                        .HasColumnName("provider_payment_charge_id");

                    b.Property<string>("TelegramPaymentChargeId")
                        .HasColumnType("text")
                        .HasColumnName("telegram_payment_charge_id");

                    b.Property<int>("TotalAmount")
                        .HasColumnType("integer")
                        .HasColumnName("total_amount");

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_payments_customer_id");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("ShadowGaze.Data.Models.Database.TelegramFiles.BotSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("SectionName")
                        .HasColumnType("text")
                        .HasColumnName("section_name");

                    b.Property<int?>("TelegramFileId")
                        .HasColumnType("integer")
                        .HasColumnName("telegram_file_id");

                    b.HasKey("Id")
                        .HasName("pk_bot_sections");

                    b.HasIndex("TelegramFileId")
                        .HasDatabaseName("ix_bot_sections_telegram_file_id");

                    b.ToTable("bot_sections", (string)null);
                });

            modelBuilder.Entity("ShadowGaze.Data.Models.Database.TelegramFiles.TelegramFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("FileId")
                        .HasColumnType("text")
                        .HasColumnName("file_id");

                    b.Property<int>("FileType")
                        .HasColumnType("integer")
                        .HasColumnName("file_type");

                    b.Property<string>("FileUniqueId")
                        .HasColumnType("text")
                        .HasColumnName("file_unique_id");

                    b.HasKey("Id")
                        .HasName("pk_telegram_files");

                    b.ToTable("telegram_files", (string)null);
                });

            modelBuilder.Entity("ShadowGaze.Data.Models.Database.Xray", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Host")
                        .HasColumnType("text")
                        .HasColumnName("host");

                    b.Property<string>("Password")
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Path")
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.Property<int>("Port")
                        .HasColumnType("integer")
                        .HasColumnName("port");

                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_xrays");

                    b.ToTable("xrays", (string)null);
                });

            modelBuilder.Entity("ShadowGaze.Data.Models.Database.Customer", b =>
                {
                    b.HasOne("ShadowGaze.Data.Models.Database.Endpoint", "Endpoint")
                        .WithOne()
                        .HasForeignKey("ShadowGaze.Data.Models.Database.Customer", "EndpointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_customers_endpoints_endpoint_id");

                    b.Navigation("Endpoint");
                });

            modelBuilder.Entity("ShadowGaze.Data.Models.Database.Endpoint", b =>
                {
                    b.HasOne("ShadowGaze.Data.Models.Database.Xray", "Xray")
                        .WithMany()
                        .HasForeignKey("XrayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_endpoints_xrays_xray_id");

                    b.Navigation("Xray");
                });

            modelBuilder.Entity("ShadowGaze.Data.Models.Database.Instructions.PlatformInstruction", b =>
                {
                    b.HasOne("ShadowGaze.Data.Models.Database.TelegramFiles.TelegramFile", "TelegramFile")
                        .WithMany()
                        .HasForeignKey("TelegramFileId")
                        .HasConstraintName("fk_platform_instructions_telegram_files_telegram_file_id");

                    b.Navigation("TelegramFile");
                });

            modelBuilder.Entity("ShadowGaze.Data.Models.Database.Payment", b =>
                {
                    b.HasOne("ShadowGaze.Data.Models.Database.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_payments_customers_customer_id");
                });

            modelBuilder.Entity("ShadowGaze.Data.Models.Database.TelegramFiles.BotSection", b =>
                {
                    b.HasOne("ShadowGaze.Data.Models.Database.TelegramFiles.TelegramFile", "TelegramFile")
                        .WithMany()
                        .HasForeignKey("TelegramFileId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_bot_sections_telegram_files_telegram_file_id");

                    b.Navigation("TelegramFile");
                });
#pragma warning restore 612, 618
        }
    }
}
