// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShadowGaze.Data.Services.Database;

#nullable disable

namespace ShadowGaze.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ShadowGaze.Data.Models.Database.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Balance")
                        .HasColumnType("double precision")
                        .HasColumnName("balance");

                    b.Property<int>("EndpointId")
                        .HasColumnType("integer")
                        .HasColumnName("endpoint_id");

                    b.Property<string>("TelegramName")
                        .HasColumnType("text")
                        .HasColumnName("telegram_name");

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.HasIndex("EndpointId")
                        .IsUnique()
                        .HasDatabaseName("ix_customers_endpoint_id");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("ShadowGaze.Data.Models.Database.Endpoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<int>("InboundId")
                        .HasColumnType("integer")
                        .HasColumnName("inbound_id");

                    b.Property<int>("XrayId")
                        .HasColumnType("integer")
                        .HasColumnName("xray_id");

                    b.HasKey("Id")
                        .HasName("pk_endpoints");

                    b.HasIndex("XrayId")
                        .HasDatabaseName("ix_endpoints_xray_id");

                    b.ToTable("endpoints", (string)null);
                });

            modelBuilder.Entity("ShadowGaze.Data.Models.Database.Xray", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("Password")
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Port")
                        .HasColumnType("text")
                        .HasColumnName("port");

                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_xrays");

                    b.ToTable("xrays", (string)null);
                });

            modelBuilder.Entity("ShadowGaze.Data.Models.Database.Customer", b =>
                {
                    b.HasOne("ShadowGaze.Data.Models.Database.Endpoint", "Endpoint")
                        .WithOne()
                        .HasForeignKey("ShadowGaze.Data.Models.Database.Customer", "EndpointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_customers_endpoints_endpoint_id");

                    b.Navigation("Endpoint");
                });

            modelBuilder.Entity("ShadowGaze.Data.Models.Database.Endpoint", b =>
                {
                    b.HasOne("ShadowGaze.Data.Models.Database.Xray", "Xray")
                        .WithMany()
                        .HasForeignKey("XrayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_endpoints_xrays_xray_id");

                    b.Navigation("Xray");
                });
#pragma warning restore 612, 618
        }
    }
}
