// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShadowGaze.Data.Services.Database;

#nullable disable

namespace ShadowGaze.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ShadowGaze.Data.Models.Database.Connection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConnectionString")
                        .HasColumnType("text")
                        .HasColumnName("connection_string");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<int>("VlessInboundId")
                        .HasColumnType("integer")
                        .HasColumnName("vless_inbound_id");

                    b.HasKey("Id")
                        .HasName("pk_connections");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_connections_customer_id");

                    b.HasIndex("VlessInboundId")
                        .IsUnique()
                        .HasDatabaseName("ix_connections_vless_inbound_id");

                    b.ToTable("connections", (string)null);
                });

            modelBuilder.Entity("ShadowGaze.Data.Models.Database.ConnectionButton", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ButtonName")
                        .HasColumnType("text")
                        .HasColumnName("button_name");

                    b.Property<int>("InboundId")
                        .HasColumnType("integer")
                        .HasColumnName("inbound_id");

                    b.HasKey("Id")
                        .HasName("pk_connection_buttons");

                    b.HasIndex("InboundId")
                        .IsUnique()
                        .HasDatabaseName("ix_connection_buttons_inbound_id");

                    b.ToTable("connection_buttons", (string)null);
                });

            modelBuilder.Entity("ShadowGaze.Data.Models.Database.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("expiry_date");

                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_id");

                    b.Property<string>("TelegramName")
                        .HasColumnType("text")
                        .HasColumnName("telegram_name");

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("ShadowGaze.Data.Models.Database.Inbound", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiUri")
                        .HasColumnType("text")
                        .HasColumnName("api_uri");

                    b.Property<string>("ConnectionName")
                        .HasColumnType("text")
                        .HasColumnName("connection_name");

                    b.Property<string>("ConnectionUri")
                        .HasColumnType("text")
                        .HasColumnName("connection_uri");

                    b.Property<string>("Flow")
                        .HasColumnType("text")
                        .HasColumnName("flow");

                    b.Property<string>("InboundTag")
                        .HasColumnType("text")
                        .HasColumnName("inbound_tag");

                    b.Property<string>("Network")
                        .HasColumnType("text")
                        .HasColumnName("network");

                    b.Property<bool>("Obsolete")
                        .HasColumnType("boolean")
                        .HasColumnName("obsolete");

                    b.Property<string>("Protocol")
                        .HasColumnType("text")
                        .HasColumnName("protocol");

                    b.Property<string>("PublicKey")
                        .HasColumnType("text")
                        .HasColumnName("public_key");

                    b.Property<string>("Security")
                        .HasColumnType("text")
                        .HasColumnName("security");

                    b.Property<string>("ServerName")
                        .HasColumnType("text")
                        .HasColumnName("server_name");

                    b.Property<string>("ShortId")
                        .HasColumnType("text")
                        .HasColumnName("short_id");

                    b.HasKey("Id")
                        .HasName("pk_inbounds");

                    b.ToTable("inbounds", (string)null);
                });

            modelBuilder.Entity("ShadowGaze.Data.Models.Database.Instructions.PlatformInstruction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationName")
                        .HasColumnType("text")
                        .HasColumnName("application_name");

                    b.Property<string>("ApplicationUrl")
                        .HasColumnType("text")
                        .HasColumnName("application_url");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("Platform")
                        .HasColumnType("integer")
                        .HasColumnName("platform");

                    b.Property<int?>("TelegramFileId")
                        .HasColumnType("integer")
                        .HasColumnName("telegram_file_id");

                    b.HasKey("Id")
                        .HasName("pk_platform_instructions");

                    b.HasIndex("TelegramFileId")
                        .HasDatabaseName("ix_platform_instructions_telegram_file_id");

                    b.ToTable("platform_instructions", (string)null);
                });

            modelBuilder.Entity("ShadowGaze.Data.Models.Database.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Currency")
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<string>("InvoicePayload")
                        .HasColumnType("text")
                        .HasColumnName("invoice_payload");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("payment_date");

                    b.Property<string>("ProviderPaymentChargeId")
                        .HasColumnType("text")
                        .HasColumnName("provider_payment_charge_id");

                    b.Property<string>("TelegramPaymentChargeId")
                        .HasColumnType("text")
                        .HasColumnName("telegram_payment_charge_id");

                    b.Property<int>("TotalAmount")
                        .HasColumnType("integer")
                        .HasColumnName("total_amount");

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_payments_customer_id");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("ShadowGaze.Data.Models.Database.PromotionalCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval")
                        .HasColumnName("duration");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("end_date");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_promotional_codes");

                    b.ToTable("promotional_codes", (string)null);
                });

            modelBuilder.Entity("ShadowGaze.Data.Models.Database.PromotionalCodeUsage", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<int>("PromotionalCodeId")
                        .HasColumnType("integer")
                        .HasColumnName("promotional_code_id");

                    b.HasKey("CustomerId", "PromotionalCodeId")
                        .HasName("pk_promotional_code_usages");

                    b.HasIndex("PromotionalCodeId")
                        .HasDatabaseName("ix_promotional_code_usages_promotional_code_id");

                    b.ToTable("promotional_code_usages", (string)null);
                });

            modelBuilder.Entity("ShadowGaze.Data.Models.Database.TelegramFiles.BotSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("SectionName")
                        .HasColumnType("text")
                        .HasColumnName("section_name");

                    b.Property<int?>("TelegramFileId")
                        .HasColumnType("integer")
                        .HasColumnName("telegram_file_id");

                    b.HasKey("Id")
                        .HasName("pk_bot_sections");

                    b.HasIndex("TelegramFileId")
                        .HasDatabaseName("ix_bot_sections_telegram_file_id");

                    b.ToTable("bot_sections", (string)null);
                });

            modelBuilder.Entity("ShadowGaze.Data.Models.Database.TelegramFiles.TelegramFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("FileId")
                        .HasColumnType("text")
                        .HasColumnName("file_id");

                    b.Property<int>("FileType")
                        .HasColumnType("integer")
                        .HasColumnName("file_type");

                    b.Property<string>("FileUniqueId")
                        .HasColumnType("text")
                        .HasColumnName("file_unique_id");

                    b.HasKey("Id")
                        .HasName("pk_telegram_files");

                    b.ToTable("telegram_files", (string)null);
                });

            modelBuilder.Entity("ShadowGaze.Data.Models.Database.Connection", b =>
                {
                    b.HasOne("ShadowGaze.Data.Models.Database.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_connections_customers_customer_id");

                    b.HasOne("ShadowGaze.Data.Models.Database.Inbound", null)
                        .WithOne()
                        .HasForeignKey("ShadowGaze.Data.Models.Database.Connection", "VlessInboundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_connections_inbounds_vless_inbound_id");
                });

            modelBuilder.Entity("ShadowGaze.Data.Models.Database.ConnectionButton", b =>
                {
                    b.HasOne("ShadowGaze.Data.Models.Database.Inbound", null)
                        .WithOne()
                        .HasForeignKey("ShadowGaze.Data.Models.Database.ConnectionButton", "InboundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_connection_buttons_inbounds_inbound_id");
                });

            modelBuilder.Entity("ShadowGaze.Data.Models.Database.Instructions.PlatformInstruction", b =>
                {
                    b.HasOne("ShadowGaze.Data.Models.Database.TelegramFiles.TelegramFile", "TelegramFile")
                        .WithMany()
                        .HasForeignKey("TelegramFileId")
                        .HasConstraintName("fk_platform_instructions_telegram_files_telegram_file_id");

                    b.Navigation("TelegramFile");
                });

            modelBuilder.Entity("ShadowGaze.Data.Models.Database.Payment", b =>
                {
                    b.HasOne("ShadowGaze.Data.Models.Database.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_payments_customers_customer_id");
                });

            modelBuilder.Entity("ShadowGaze.Data.Models.Database.PromotionalCodeUsage", b =>
                {
                    b.HasOne("ShadowGaze.Data.Models.Database.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_promotional_code_usages_customers_customer_id");

                    b.HasOne("ShadowGaze.Data.Models.Database.PromotionalCode", null)
                        .WithMany()
                        .HasForeignKey("PromotionalCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_promotional_code_usages_promotional_codes_promotional_code_");
                });

            modelBuilder.Entity("ShadowGaze.Data.Models.Database.TelegramFiles.BotSection", b =>
                {
                    b.HasOne("ShadowGaze.Data.Models.Database.TelegramFiles.TelegramFile", "TelegramFile")
                        .WithMany()
                        .HasForeignKey("TelegramFileId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_bot_sections_telegram_files_telegram_file_id");

                    b.Navigation("TelegramFile");
                });
#pragma warning restore 612, 618
        }
    }
}
